name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Test and generate coverage report
        run: npm run coverage

